DB_NAME: greeting_test
DB_PORT: 5432
DB_HOST: 127.0.0.1
DB_PASSWORD: postgres
DB_USERNAME: postgres
LEAK_THRESHOLD: 60000
DB_MAX_POOL_SIZE: 2
GREET_TIMEOUT_IN_SEC: 2
KAFKA_BROKERS: localhost:9092
KAFKA_CLIENT_ID: client1
KAFKA_MESSAGE_COUNT: 1000
KAFKA_GROUP_ID_CONFIG: consumerGroup1
GREET_TOPIC_NAME: demo
KAFKA_MAX_NO_MESSAGE_FOUND_COUNT: 100
KAFKA_OFFSET_RESET_LATEST: latest
OFFSET_RESET_EARLIER: earliest
RETRY_BACKOFF_MS_CONFIG: 1000
REQUEST_TIMEOUT_MS_CONFIG: 15000
RETRIES_CONFIG: 3
MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION: 1
KAFKA_BOOTSTRAP_SERVERS: http://localhost:9092
KAFKA_LEGACY_BOOTSTRAP_SERVERS: http://localhost:9092

